//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAnuncioPatrocinador
    {
        public int apaid { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<int> aid { get; set; }
    
        public virtual tbAnuncio tbAnuncio { get; set; }
        public virtual tbConsumidor tbConsumidor { get; set; }
    }
}
