//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAnuncioArea
    {
        public tbAnuncioArea()
        {
            this.tbAnuncio = new HashSet<tbAnuncio>();
        }
    
        public int aaid { get; set; }
        public string tituloAnuncioArea { get; set; }
    
        public virtual ICollection<tbAnuncio> tbAnuncio { get; set; }
    }
}
