//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAnunciante
    {
        public tbAnunciante()
        {
            this.tbAnuncianteEndereco = new HashSet<tbAnuncianteEndereco>();
            this.tbAnunciantePatrocinador = new HashSet<tbAnunciantePatrocinador>();
            this.tbAnuncianteTelefone = new HashSet<tbAnuncianteTelefone>();
            this.tbAnuncio = new HashSet<tbAnuncio>();
            this.tbCampanha = new HashSet<tbCampanha>();
            this.tbConsumidorPontos = new HashSet<tbConsumidorPontos>();
            this.tbCreditoCompra = new HashSet<tbCreditoCompra>();
            this.tbCreditoDesconta = new HashSet<tbCreditoDesconta>();
            this.tbDestaqueAnunciante = new HashSet<tbDestaqueAnunciante>();
            this.tbTransacaoXml = new HashSet<tbTransacaoXml>();
        }
    
        public int pid { get; set; }
        public string cnpj { get; set; }
        public string razaoSocial { get; set; }
        public string nmFantasia { get; set; }
        public string contato { get; set; }
        public string telResidencial { get; set; }
        public string telComercial { get; set; }
        public string telCelular1 { get; set; }
        public string telCelular2 { get; set; }
        public string ie { get; set; }
        public string im { get; set; }
        public string email { get; set; }
        public string site { get; set; }
        public string obs { get; set; }
        public Nullable<int> cpid { get; set; }
        public Nullable<int> raid { get; set; }
        public Nullable<int> tid { get; set; }
        public Nullable<decimal> saldoCreditos { get; set; }
        public Nullable<int> leuTermo { get; set; }
        public Nullable<int> uid { get; set; }
        public string cpf { get; set; }
        public string rg { get; set; }
        public string pis { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<System.DateTime> dtNascimento { get; set; }
        public Nullable<bool> ativo { get; set; }
        public Nullable<int> ansid { get; set; }
    
        public virtual tbAnuncianteStatus tbAnuncianteStatus { get; set; }
        public virtual tbCondicaoPagto tbCondicaoPagto { get; set; }
        public virtual ICollection<tbAnuncianteEndereco> tbAnuncianteEndereco { get; set; }
        public virtual ICollection<tbAnunciantePatrocinador> tbAnunciantePatrocinador { get; set; }
        public virtual ICollection<tbAnuncianteTelefone> tbAnuncianteTelefone { get; set; }
        public virtual ICollection<tbAnuncio> tbAnuncio { get; set; }
        public virtual ICollection<tbCampanha> tbCampanha { get; set; }
        public virtual ICollection<tbConsumidorPontos> tbConsumidorPontos { get; set; }
        public virtual ICollection<tbCreditoCompra> tbCreditoCompra { get; set; }
        public virtual ICollection<tbCreditoDesconta> tbCreditoDesconta { get; set; }
        public virtual ICollection<tbDestaqueAnunciante> tbDestaqueAnunciante { get; set; }
        public virtual ICollection<tbTransacaoXml> tbTransacaoXml { get; set; }
        public virtual tbRamoAtividade tbRamoAtividade { get; set; }
        public virtual tbTos tbTos { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
