//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAnuncio
    {
        public tbAnuncio()
        {
            this.tbAnuncioFuncionalidade = new HashSet<tbAnuncioFuncionalidade>();
            this.tbAnuncioImg = new HashSet<tbAnuncioImg>();
            this.tbCampanhaAnuncio = new HashSet<tbCampanhaAnuncio>();
            this.tbPontosRede = new HashSet<tbPontosRede>();
        }
    
        public int aid { get; set; }
        public string tituloAnuncio { get; set; }
        public string url { get; set; }
        public string dsAnuncio { get; set; }
        public string videoAnuncio { get; set; }
        public Nullable<int> raid { get; set; }
        public Nullable<int> comentar { get; set; }
        public Nullable<int> curtir { get; set; }
        public Nullable<int> compartilhar { get; set; }
    
        public virtual ICollection<tbAnuncioFuncionalidade> tbAnuncioFuncionalidade { get; set; }
        public virtual ICollection<tbAnuncioImg> tbAnuncioImg { get; set; }
        public virtual ICollection<tbCampanhaAnuncio> tbCampanhaAnuncio { get; set; }
        public virtual ICollection<tbPontosRede> tbPontosRede { get; set; }
        public virtual tbRamoAtividade tbRamoAtividade { get; set; }
    }
}
