//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAnuncianteDestaqueStatus
    {
        public tbAnuncianteDestaqueStatus()
        {
            this.tbAnuncianteDestaque = new HashSet<tbAnuncianteDestaque>();
        }
    
        public int adsid { get; set; }
        public string dsAnuncianteDestaqueStatus { get; set; }
    
        public virtual ICollection<tbAnuncianteDestaque> tbAnuncianteDestaque { get; set; }
    }
}
