//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAnuncianteDestaque
    {
        public tbAnuncianteDestaque()
        {
            this.tbCreditoDesconta = new HashSet<tbCreditoDesconta>();
        }
    
        public int adid { get; set; }
        public int pid { get; set; }
        public int did { get; set; }
        public int adsid { get; set; }
        public double qtCreditoCompra { get; set; }
        public System.DateTime dtAssociacao { get; set; }
    
        public virtual tbAnunciante tbAnunciante { get; set; }
        public virtual ICollection<tbCreditoDesconta> tbCreditoDesconta { get; set; }
        public virtual tbAnuncianteDestaqueStatus tbAnuncianteDestaqueStatus { get; set; }
        public virtual tbDestaque tbDestaque { get; set; }
    }
}
