//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAnuncioStatus
    {
        public tbAnuncioStatus()
        {
            this.tbAnuncio = new HashSet<tbAnuncio>();
            this.tbAnuncioImgLog = new HashSet<tbAnuncioImgLog>();
            this.tbConfigPadrao = new HashSet<tbConfigPadrao>();
            this.tbConfigPadrao1 = new HashSet<tbConfigPadrao>();
        }
    
        public int asid { get; set; }
        public string dsStatus { get; set; }
    
        public virtual ICollection<tbAnuncio> tbAnuncio { get; set; }
        public virtual ICollection<tbAnuncioImgLog> tbAnuncioImgLog { get; set; }
        public virtual ICollection<tbConfigPadrao> tbConfigPadrao { get; set; }
        public virtual ICollection<tbConfigPadrao> tbConfigPadrao1 { get; set; }
    }
}
