//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAnuncioImg
    {
        public long imgid { get; set; }
        public string url_imagem { get; set; }
        public string tipo { get; set; }
        public string tamanho { get; set; }
        public Nullable<int> iditem { get; set; }
        public Nullable<int> aid { get; set; }
        public Nullable<int> actid { get; set; }
        public Nullable<bool> ativo { get; set; }
    
        public virtual tbAnuncio tbAnuncio { get; set; }
        public virtual tbAnuncioCodTemp tbAnuncioCodTemp { get; set; }
    }
}
