//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBan
    {
        public int baid { get; set; }
        public int btid { get; set; }
        public int uid { get; set; }
        public System.DateTime dtOcorrido { get; set; }
    
        public virtual tbBanTipo tbBanTipo { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
