//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBanner
    {
        public tbBanner()
        {
            this.tbBannerImg = new HashSet<tbBannerImg>();
        }
    
        public int bid { get; set; }
        public string tituloBanner { get; set; }
    
        public virtual ICollection<tbBannerImg> tbBannerImg { get; set; }
    }
}
