//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBairro
    {
        public tbBairro()
        {
            this.tbCep = new HashSet<tbCep>();
        }
    
        public int baiid { get; set; }
        public string nomeBairro { get; set; }
        public int cid { get; set; }
        public string abrevBairro { get; set; }
        public string uf { get; set; }
    
        public virtual ICollection<tbCep> tbCep { get; set; }
        public virtual tbCidade tbCidade { get; set; }
    }
}
