//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBannerImg
    {
        public int imgid { get; set; }
        public int bid { get; set; }
        public int ativo { get; set; }
        public string img_banner { get; set; }
    
        public virtual tbBanner tbBanner { get; set; }
    }
}
