//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCampanhaAnuncioStatus
    {
        public tbCampanhaAnuncioStatus()
        {
            this.tbConfigPadrao = new HashSet<tbConfigPadrao>();
            this.tbCampanhaAnuncio = new HashSet<tbCampanhaAnuncio>();
        }
    
        public int casid { get; set; }
        public string dsCampAnunStatus { get; set; }
    
        public virtual ICollection<tbConfigPadrao> tbConfigPadrao { get; set; }
        public virtual ICollection<tbCampanhaAnuncio> tbCampanhaAnuncio { get; set; }
    }
}
