//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCampanhaAnuncioConsumidor
    {
        public tbCampanhaAnuncioConsumidor()
        {
            this.tbPremioConsumidor = new HashSet<tbPremioConsumidor>();
        }
    
        public int cacid { get; set; }
        public int caid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<bool> waitTimeOut { get; set; }
    
        public virtual tbCampanhaAnuncio tbCampanhaAnuncio { get; set; }
        public virtual ICollection<tbPremioConsumidor> tbPremioConsumidor { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
