//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCampanhaAnuncio
    {
        public tbCampanhaAnuncio()
        {
            this.tbCampanhaAnuncioConsumidor = new HashSet<tbCampanhaAnuncioConsumidor>();
            this.tbCampanhaAnuncioLocalizacao = new HashSet<tbCampanhaAnuncioLocalizacao>();
        }
    
        public int caid { get; set; }
        public int aid { get; set; }
        public int cid { get; set; }
        public int casid { get; set; }
        public Nullable<int> qtCliqueMax { get; set; }
        public Nullable<int> pcid { get; set; }
        public Nullable<System.DateTime> dtMovimento { get; set; }
    
        public virtual tbAnuncio tbAnuncio { get; set; }
        public virtual tbCampanha tbCampanha { get; set; }
        public virtual ICollection<tbCampanhaAnuncioConsumidor> tbCampanhaAnuncioConsumidor { get; set; }
        public virtual ICollection<tbCampanhaAnuncioLocalizacao> tbCampanhaAnuncioLocalizacao { get; set; }
        public virtual tbCampanhaAnuncioStatus tbCampanhaAnuncioStatus { get; set; }
        public virtual tbPacoteClique tbPacoteClique { get; set; }
    }
}
