//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCalculoCondicaoPagto
    {
        public tbCalculoCondicaoPagto()
        {
            this.tbCalculoCondicao = new HashSet<tbCalculoCondicao>();
        }
    
        public int ccpid { get; set; }
        public Nullable<int> calculo { get; set; }
        public int numDias { get; set; }
        public int diaMes { get; set; }
        public Nullable<double> valor { get; set; }
    
        public virtual ICollection<tbCalculoCondicao> tbCalculoCondicao { get; set; }
    }
}
