//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCampanhaTmp
    {
        public tbCampanhaTmp()
        {
            this.tbCampanha = new HashSet<tbCampanha>();
            this.tbCampanhaAnuncio = new HashSet<tbCampanhaAnuncio>();
        }
    
        public int ctid { get; set; }
        public string sessionID { get; set; }
    
        public virtual ICollection<tbCampanha> tbCampanha { get; set; }
        public virtual ICollection<tbCampanhaAnuncio> tbCampanhaAnuncio { get; set; }
    }
}
