//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCampanhaAnuncio
    {
        public tbCampanhaAnuncio()
        {
            this.tbCampanhaAnuncioConsumidor = new HashSet<tbCampanhaAnuncioConsumidor>();
        }
    
        public int caid { get; set; }
        public int aid { get; set; }
        public Nullable<int> cid { get; set; }
        public int casid { get; set; }
        public Nullable<System.DateTime> dtMovimento { get; set; }
        public Nullable<int> ctid { get; set; }
        public Nullable<int> contCliquesFinal { get; set; }
        public Nullable<int> contCliquesAtual { get; set; }
        public Nullable<int> contCurtidas { get; set; }
        public Nullable<int> contComentarios { get; set; }
        public Nullable<int> contCompartilhadas { get; set; }
    
        public virtual tbAnuncio tbAnuncio { get; set; }
        public virtual tbCampanha tbCampanha { get; set; }
        public virtual ICollection<tbCampanhaAnuncioConsumidor> tbCampanhaAnuncioConsumidor { get; set; }
        public virtual tbCampanhaAnuncioStatus tbCampanhaAnuncioStatus { get; set; }
        public virtual tbCampanhaTmp tbCampanhaTmp { get; set; }
    }
}
