//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCep
    {
        public tbCep()
        {
            this.tbAnuncianteEndereco = new HashSet<tbAnuncianteEndereco>();
        }
    
        public int cepid { get; set; }
        public string dsLogradouro { get; set; }
        public string cep { get; set; }
        public Nullable<int> eid { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<int> baiid { get; set; }
        public string tipoLogradouro { get; set; }
        public string uf { get; set; }
        public string abrevLogradouro { get; set; }
        public Nullable<int> tlid { get; set; }
    
        public virtual ICollection<tbAnuncianteEndereco> tbAnuncianteEndereco { get; set; }
        public virtual tbBairro tbBairro { get; set; }
        public virtual tbCidade tbCidade { get; set; }
        public virtual tbEstado tbEstado { get; set; }
        public virtual tbTipoLogradouro tbTipoLogradouro { get; set; }
    }
}
