//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCidade
    {
        public tbCidade()
        {
            this.tbCampanhaAnuncioLocalizacao = new HashSet<tbCampanhaAnuncioLocalizacao>();
            this.tbBairro = new HashSet<tbBairro>();
            this.tbCep = new HashSet<tbCep>();
        }
    
        public int cid { get; set; }
        public string nomeCidade { get; set; }
        public int eid { get; set; }
        public string cep_cidade { get; set; }
        public string uf { get; set; }
        public string dsCidade { get; set; }
    
        public virtual ICollection<tbCampanhaAnuncioLocalizacao> tbCampanhaAnuncioLocalizacao { get; set; }
        public virtual tbEstado tbEstado { get; set; }
        public virtual ICollection<tbBairro> tbBairro { get; set; }
        public virtual ICollection<tbCep> tbCep { get; set; }
    }
}
