//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbConsumidorPontos
    {
        public int cpoid { get; set; }
        public Nullable<double> qtdPontos { get; set; }
        public Nullable<System.DateTime> dtMovimento { get; set; }
        public Nullable<int> cposid { get; set; }
        public string descOrigem { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> cid { get; set; }
    
        public virtual tbAnunciante tbAnunciante { get; set; }
        public virtual tbConsumidor tbConsumidor { get; set; }
        public virtual tbConsumidorPontosStatus tbConsumidorPontosStatus { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
