//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbConsumidorPontosStatus
    {
        public tbConsumidorPontosStatus()
        {
            this.tbConfigPadrao = new HashSet<tbConfigPadrao>();
            this.tbConsumidorPontos = new HashSet<tbConsumidorPontos>();
        }
    
        public int cposid { get; set; }
        public string descStatus { get; set; }
    
        public virtual ICollection<tbConfigPadrao> tbConfigPadrao { get; set; }
        public virtual ICollection<tbConsumidorPontos> tbConsumidorPontos { get; set; }
    }
}
