//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCredito
    {
        public tbCredito()
        {
            this.tbCreditoCompra = new HashSet<tbCreditoCompra>();
            this.tbCreditoPromocional = new HashSet<tbCreditoPromocional>();
        }
    
        public int crid { get; set; }
        public Nullable<double> qtCredito { get; set; }
        public Nullable<decimal> vlCredito { get; set; }
        public Nullable<bool> promocional { get; set; }
        public string tituloPacote { get; set; }
        public string dsCredito { get; set; }
    
        public virtual ICollection<tbCreditoCompra> tbCreditoCompra { get; set; }
        public virtual ICollection<tbCreditoPromocional> tbCreditoPromocional { get; set; }
    }
}
