//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCreditoCompra
    {
        public int ccid { get; set; }
        public int pid { get; set; }
        public int crid { get; set; }
        public Nullable<System.DateTime> dtCompra { get; set; }
        public Nullable<int> crsid { get; set; }
    
        public virtual tbAnunciante tbAnunciante { get; set; }
        public virtual tbCredito tbCredito { get; set; }
        public virtual tbCreditoStatus tbCreditoStatus { get; set; }
    }
}
