//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCreditoPromocional
    {
        public int crpid { get; set; }
        public Nullable<int> crid { get; set; }
        public Nullable<System.DateTime> dtInicioPromocao { get; set; }
        public Nullable<System.DateTime> dtFinalPromocao { get; set; }
        public Nullable<int> uid { get; set; }
    
        public virtual tbCredito tbCredito { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
