//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCreditoDesconta
    {
        public int dcid { get; set; }
        public Nullable<double> saldoCreditoIni { get; set; }
        public Nullable<double> saldoCreditoFin { get; set; }
        public Nullable<System.DateTime> dtOcorrido { get; set; }
        public Nullable<int> daid { get; set; }
        public Nullable<int> pid { get; set; }
    
        public virtual tbAnunciante tbAnunciante { get; set; }
        public virtual tbDestaqueAnunciante tbDestaqueAnunciante { get; set; }
    }
}
