//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDestaque
    {
        public tbDestaque()
        {
            this.tbAnuncianteDestaque = new HashSet<tbAnuncianteDestaque>();
            this.tbCampanha = new HashSet<tbCampanha>();
            this.tbPremioDestaque = new HashSet<tbPremioDestaque>();
        }
    
        public int did { get; set; }
        public string tituloDestaque { get; set; }
        public Nullable<double> qtCredito { get; set; }
        public double tmpEspera { get; set; }
        public string durCampanha { get; set; }
        public double qtDurCampanha { get; set; }
        public string dsDestaque { get; set; }
        public string imgDestaque { get; set; }
    
        public virtual ICollection<tbAnuncianteDestaque> tbAnuncianteDestaque { get; set; }
        public virtual ICollection<tbCampanha> tbCampanha { get; set; }
        public virtual ICollection<tbPremioDestaque> tbPremioDestaque { get; set; }
    }
}
