//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDestaqueAnunciante
    {
        public tbDestaqueAnunciante()
        {
            this.tbCampanha = new HashSet<tbCampanha>();
            this.tbCreditoDesconta = new HashSet<tbCreditoDesconta>();
        }
    
        public int daid { get; set; }
        public Nullable<int> did { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<System.DateTime> dtMovimento { get; set; }
        public Nullable<int> dasid { get; set; }
    
        public virtual tbAnunciante tbAnunciante { get; set; }
        public virtual ICollection<tbCampanha> tbCampanha { get; set; }
        public virtual ICollection<tbCreditoDesconta> tbCreditoDesconta { get; set; }
        public virtual tbDestaque tbDestaque { get; set; }
        public virtual tbDestaqueAnuncianteStatus tbDestaqueAnuncianteStatus { get; set; }
    }
}
