//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstado
    {
        public tbEstado()
        {
            this.tbCampanhaAnuncioLocalizacao = new HashSet<tbCampanhaAnuncioLocalizacao>();
            this.tbCidade = new HashSet<tbCidade>();
            this.tbCep = new HashSet<tbCep>();
            this.tbAnuncianteEndereco = new HashSet<tbAnuncianteEndereco>();
        }
    
        public int eid { get; set; }
        public string nomeEstado { get; set; }
        public string sgEstado { get; set; }
        public Nullable<int> ibge { get; set; }
        public Nullable<int> paid { get; set; }
    
        public virtual ICollection<tbCampanhaAnuncioLocalizacao> tbCampanhaAnuncioLocalizacao { get; set; }
        public virtual ICollection<tbCidade> tbCidade { get; set; }
        public virtual ICollection<tbCep> tbCep { get; set; }
        public virtual tbPais tbPais { get; set; }
        public virtual ICollection<tbAnuncianteEndereco> tbAnuncianteEndereco { get; set; }
    }
}
