//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFuncionalidade
    {
        public tbFuncionalidade()
        {
            this.tbAnuncioFuncionalidade = new HashSet<tbAnuncioFuncionalidade>();
        }
    
        public int fid { get; set; }
        public string dsFuncionalidade { get; set; }
    
        public virtual ICollection<tbAnuncioFuncionalidade> tbAnuncioFuncionalidade { get; set; }
    }
}
