//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPermissao
    {
        public tbPermissao()
        {
            this.tbUsersPermissao = new HashSet<tbUsersPermissao>();
        }
    
        public int peid { get; set; }
        public string dsPermissao { get; set; }
    
        public virtual ICollection<tbUsersPermissao> tbUsersPermissao { get; set; }
    }
}
