//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPermissaoSubGrupo
    {
        public tbPermissaoSubGrupo()
        {
            this.tbPermissao = new HashSet<tbPermissao>();
        }
    
        public int psgid { get; set; }
        public string dsPermissaoSubGrupo { get; set; }
        public int pgid { get; set; }
    
        public virtual ICollection<tbPermissao> tbPermissao { get; set; }
        public virtual tbPermissaoGrupo tbPermissaoGrupo { get; set; }
    }
}
