//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPremioNivel
    {
        public tbPremioNivel()
        {
            this.tbPremio = new HashSet<tbPremio>();
        }
    
        public int pnid { get; set; }
        public string tituloNivelPremio { get; set; }
        public string dsPremio { get; set; }
        public string premioImg { get; set; }
    
        public virtual ICollection<tbPremio> tbPremio { get; set; }
    }
}
