//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPremio
    {
        public tbPremio()
        {
            this.tbPremioConsumidor = new HashSet<tbPremioConsumidor>();
            this.tbPremioDestaque = new HashSet<tbPremioDestaque>();
            this.tbPremioImg = new HashSet<tbPremioImg>();
        }
    
        public int prid { get; set; }
        public int pnid { get; set; }
        public string tituloPremio { get; set; }
        public string dsPremio { get; set; }
        public System.DateTime dtCriacao { get; set; }
        public Nullable<int> ativo { get; set; }
    
        public virtual tbPremioNivel tbPremioNivel { get; set; }
        public virtual ICollection<tbPremioConsumidor> tbPremioConsumidor { get; set; }
        public virtual ICollection<tbPremioDestaque> tbPremioDestaque { get; set; }
        public virtual ICollection<tbPremioImg> tbPremioImg { get; set; }
    }
}
