//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPremioImg
    {
        public int piid { get; set; }
        public int prid { get; set; }
        public string premioImg { get; set; }
    
        public virtual tbPremio tbPremio { get; set; }
    }
}
