//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRamoAtividade
    {
        public tbRamoAtividade()
        {
            this.tbAnunciante = new HashSet<tbAnunciante>();
            this.tbAnuncio = new HashSet<tbAnuncio>();
        }
    
        public int raid { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<tbAnunciante> tbAnunciante { get; set; }
        public virtual ICollection<tbAnuncio> tbAnuncio { get; set; }
    }
}
