//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoLogradouro
    {
        public tbTipoLogradouro()
        {
            this.tbCep = new HashSet<tbCep>();
        }
    
        public int tlid { get; set; }
        public string dsTipoLogradouro { get; set; }
        public string abrevTipoLogradouro { get; set; }
    
        public virtual ICollection<tbCep> tbCep { get; set; }
    }
}
