//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTos
    {
        public tbTos()
        {
            this.tbAnunciante = new HashSet<tbAnunciante>();
            this.tbConsumidor = new HashSet<tbConsumidor>();
        }
    
        public int tid { get; set; }
        public string titulo { get; set; }
        public string clausula { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<tbAnunciante> tbAnunciante { get; set; }
        public virtual ICollection<tbConsumidor> tbConsumidor { get; set; }
    }
}
