//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTransacaoXml
    {
        public int txid { get; set; }
        public string transacao { get; set; }
        public string sid { get; set; }
        public Nullable<int> pid { get; set; }
        public string chave { get; set; }
        public string credor { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> dataVencimento { get; set; }
        public string descricao { get; set; }
        public string cpf { get; set; }
        public string cep { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string bairro { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public Nullable<int> numMaximoParcelas { get; set; }
        public string campoLivre { get; set; }
        public string urlRetornoLoja { get; set; }
        public Nullable<int> txsid { get; set; }
        public Nullable<System.DateTime> dtMovimento { get; set; }
    
        public virtual tbAnunciante tbAnunciante { get; set; }
        public virtual tbTransacaoXmlStatus tbTransacaoXmlStatus { get; set; }
    }
}
