//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTransacaoXmlStatus
    {
        public tbTransacaoXmlStatus()
        {
            this.tbTransacaoXml = new HashSet<tbTransacaoXml>();
        }
    
        public int txsid { get; set; }
        public string dsStatus { get; set; }
    
        public virtual ICollection<tbTransacaoXml> tbTransacaoXml { get; set; }
    }
}
