//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsersLogAcesso
    {
        public int ulaid { get; set; }
        public int uid { get; set; }
        public System.DateTime dataHoraLog { get; set; }
        public Nullable<int> timeOutLog { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
