//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsersPermissao
    {
        public int upid { get; set; }
        public int uid { get; set; }
        public int peid { get; set; }
    
        public virtual tbPermissao tbPermissao { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
