//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwAnunciosCriadosAnunciante
    {
        public string Título { get; set; }
        public string Status { get; set; }
        public string CNPJ { get; set; }
        public string CPF { get; set; }
        public string razaoSocial { get; set; }
        public string nmFantasia { get; set; }
    }
}
