//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwAnunciosEmCampanha
    {
        public int CodAnuncio { get; set; }
        public string TituloAnuncio { get; set; }
        public string StatusAnuncio { get; set; }
        public Nullable<int> CodAnunciante { get; set; }
        public string DescCategoria { get; set; }
        public Nullable<System.DateTime> DtCriacao { get; set; }
        public int CodCampanha { get; set; }
        public string DescCampanha { get; set; }
    }
}
