//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwCampanhasAtivasAnunciante
    {
        public int CodCampanha { get; set; }
        public string TituloCampanha { get; set; }
        public string StatusCampanha { get; set; }
        public Nullable<int> CodAnunciante { get; set; }
        public System.DateTime DtInicio { get; set; }
        public System.DateTime DtTermino { get; set; }
    }
}
