//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwRelatorioAnuncianteAnuncios_Disponiveis
    {
        public int aid { get; set; }
        public string tituloAnuncio { get; set; }
        public string dsCategoria { get; set; }
        public string dsStatus { get; set; }
        public string VIDEO { get; set; }
        public string IMAGEM { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public Nullable<int> pid { get; set; }
    }
}
