//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliquemix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwRelatorioAnuncianteAnuncios_Cliques
    {
        public int aid { get; set; }
        public string tituloAnuncio { get; set; }
        public Nullable<int> cid { get; set; }
        public System.DateTime dtInicio { get; set; }
        public System.DateTime dtTermino { get; set; }
        public Nullable<int> contCliquesAtual { get; set; }
        public Nullable<int> contCliquesFinal { get; set; }
        public Nullable<int> pid { get; set; }
    }
}
